version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy/log:/var/log/nginx
      - ./reverseproxy/key/touyakun.com-key.pem:/etc/certs/touyakun.com-key.pem
      - ./reverseproxy/key/touyakun.com.pem:/etc/certs/touyakun.com.pem
      - ./reverseproxy/key/ai.touyakun.com-key.pem:/etc/certs/ai.touyakun.com-key.pem
      - ./reverseproxy/key/ai.touyakun.com.pem:/etc/certs/ai.touyakun.com.pem
    depends_on:
      - api
      - ai
  api:
    container_name: api
    tty: true
    build: ./api/
    expose:
      - 8080
    volumes:
      - ./api:/go/src/api
    depends_on:
      - db
  ai:
    container_name: ai
    build: ./ai/
    tty: true
    expose:
      - 8080
    volumes:
      - ./ai:/usr/src/ai
  db:
    image: postgres:16.2-alpine
    container_name: db
    tty: true
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
