version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy/log:/var/log/nginx
      - ./reverseproxy/key/touyakun.com-key.pem:/etc/certs/touyakun.com-key.pem
      - ./reverseproxy/key/touyakun.com.pem:/etc/certs/touyakun.com.pem
      - ./reverseproxy/key/ai.touyakun.com-key.pem:/etc/certs/ai.touyakun.com-key.pem
      - ./reverseproxy/key/ai.touyakun.com.pem:/etc/certs/ai.touyakun.com.pem
    depends_on:
      - api
      - ai
  api:
    container_name: api
    tty: true
    build: ./api/
    expose:
      - 8080
    volumes:
      - ./api:/go/src/api
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - ./api/.env
  ai:
    container_name: ai
    build: ./ai/
    tty: true
    expose:
      - 8080
    volumes:
      - ./ai:/usr/src/ai
    env_file:
      - ./ai/.env
  db:
    image: postgres:16.2-alpine
    container_name: db
    tty: true
    environment:
      - POSTGRES_DB=touyakun
      - POSTGRES_USER=touyakun
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-test:
    image: postgres:16.2-alpine
    container_name: db-test
    tty: true
    environment:
      - POSTGRES_DB=testcase
      - POSTGRES_USER=testcase
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-test-data:
