version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy/log:/var/log/nginx
      - ./reverseproxy/key/touyakun.com-key.pem:/etc/certs/touyakun.com-key.pem
      - ./reverseproxy/key/touyakun.com.pem:/etc/certs/touyakun.com.pem
    depends_on:
      - api
  api:
    container_name: api
    tty: true
    build: ./api
    expose:
      - 8080
    volumes:
      - ./api:/go/src/api
